services:
  front:
    image: front:latest
    restart: on-failure
    ports:
      - 3015:3015 # TODO get from envfile (or .env?????)
    networks:
      - local
    build:
      context: ./front
      dockerfile: Dockerfile.dev # TODO differentiate!!
    extra_hosts:
      - host.docker.internal:host-gateway
    # TODO remove after devving!
    volumes:
      - ./front/src:/app/src:ro
    env_file:
      - ./front/.env

  integra:
    image: integra:latest
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - local
    build:
      context: ./integra
      dockerfile: Dockerfile
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - ./integra/.env

  db:
    image: postgres:16.2
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=34313407A
      - POSTGRES_DB=integrabuzios
    networks:
      - local

networks:
  local:
    name: integra_buzios
